### ISSUE TITLE
GetCapabilities softwareVersion gml:version is empty

### ISSUE THREAD

**Issue by shane-axiom** [asascience-open/ncSOS#178] opened 2016-04-15 23:20 UTC
Not sure if this is a deployment issue or not, but the `softwareVersion` gml:version node on PacIOOS' ncSOS is empty:

http://oos.soest.hawaii.edu/thredds/sos/pacioos/aws/himbagg?service=SOS&request=GetCapabilities&acceptVersions=1.0.0

I checked with John and he said they're running 1.2.1. It would be helpful for debugging if  `softwareVersion` was set.

**Comment by cheryldmorse** [comment] 2017-01-03 16:55
This issue is related to a specific issue with Tomcat version 8.0.24. The issue is making it so that the ncSOS manifest file can't be accessed. This problem goes away with Tomcat 8.0.26.

In order to deal with this issue  the following workaround was added to ncSOS:
- When ncSOS can't retrieve the version from the manifest it will parse the name of the ncSOS jar file to determine the version.

This will be included in ncSOS version 1.4

**Closed by cheryldmorse** 2017-01-03 16:55 UTC
